<a href="https://colab.research.google.com/github/jyotish123-hub/Data-Visualization/blob/main/11sep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import seaborn as sns
df=sns.load_dataset("titanic")
df.tail(3)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [3]:
df.groupby("sex").size()

/tmp/ipykernel_8083/4213776571.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("sex").size()

sex
Male      157
Female     87
dtype: int64

In [4]:
df.groupby("sex").count()

/tmp/ipykernel_8083/2367943833.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("sex").count()

        total_bill  tip  smoker  day  time  size
sex
Male           157  157     157  157   157   157
Female          87   87      87   87    87    87

In [6]:
df.groupby("sex")["age"].mean()

sex
female    27.915709
male      30.726645
Name: age, dtype: float64

In [7]:
df.groupby("sex")["age"].max()

sex
female    63.0
male      80.0
Name: age, dtype: float64

In [8]:
df.groupby("sex")["age"].agg(["min","max","mean","std","var"])

         min   max       mean        std         var
sex
female  0.75  63.0  27.915709  14.110146  199.096233
male    0.42  80.0  30.726645  14.678201  215.449579

In [14]:
df.groupby("sex")[["age","fare"]].agg(["min","max","mean","std","var"])

         age                                          fare            \
         min   max       mean        std         var   min       max
sex
female  0.75  63.0  27.915709  14.110146  199.096233  6.75  512.3292
male    0.42  80.0  30.726645  14.678201  215.449579  0.00  512.3292


             mean        std          var
sex
female  44.479818  57.997698  3363.732930
male    25.523893  43.138263  1860.909702

In [15]:
df.groupby("sex")[["age","fare"]].min()

         age  fare
sex
female  0.75  6.75
male    0.42  0.00

In [16]:
df.groupby("sex")[["age","fare"]].agg({"age":"min","fare":"max"})

         age      fare
sex
female  0.75  512.3292
male    0.42  512.3292

In [17]:
df.groupby("pclass").size()

pclass
1    216
2    184
3    491
dtype: int64

In [24]:
df.groupby(["pclass","sex"])["fare"].max()

                   fare
pclass sex
1      female  512.3292
       male    512.3292
2      female   65.0000
       male     73.5000
3      female   69.5500
       male     69.5500

In [25]:
df.groupby(["pclass","sex"]).agg({"fare":"max"})

                   fare
pclass sex
1      female  512.3292
       male    512.3292
2      female   65.0000
       male     73.5000
3      female   69.5500
       male     69.5500

In [30]:
df.groupby(["pclass","sex"])["survived"].size()

pclass  sex
1       female     94
        male      122
2       female     76
        male      108
3       female    144
        male      347
Name: survived, dtype: int64