<a href="https://colab.research.google.com/github/jyotish123-hub/Data-Visualization/blob/main/11sep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import seaborn as sns
df=sns.load_dataset("titanic")
df.tail(3)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [3]:
df.groupby("sex").size()

/tmp/ipykernel_8083/4213776571.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("sex").size()

sex
Male      157
Female     87
dtype: int64

In [4]:
df.groupby("sex").count()

/tmp/ipykernel_8083/2367943833.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("sex").count()

        total_bill  tip  smoker  day  time  size
sex
Male           157  157     157  157   157   157
Female          87   87      87   87    87    87